### ISSUE TITLE
Paths should be IO instead of Str

### ISSUE THREAD

**Issue by taboege** [scriptkitties/p6-Config#5]
The $path arguments in Config's and Config::Parser's .read and .write methods are Str. Shouldn't they be IO or, better yet, an IO() coercer?

I ran into this issue while adding tests for pull requests to add write methods to the json and yaml parsers (the Temp::Path module I use for the tests returns IO::Path instead of Str). I wanted to discuss this first as, on the one hand, IO() seems to be the more appropriate type, but changing Config in that way would break all the existing Config::Parser:: modules, because they explicitly implement the (Str $path) signature.

Should: (1) nothing be done (I add an IO::Path -> Str conversion in my tests), (2) a second multi for IO be added (essentially redundant if you could use an IO() coercer), or (3) Str be changed to IO() coordinated with the parser repos?

**Comment by Tyil** [comment]
Hi @taboege, and sorry for the slow reply.

To maintain backwards compatibility, I would personally go for a `multi`, to allow either a `Str` or an `IO` as argument to `.read` and `.write`. I will try to have a patch for this by next weekend, as Im still catching up on a lot of very old GitHub issues.
