### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by AntonOks** [scriptkitties/p6-Config#8]
WARNING: Version mismatch for Config ("https://github.com/scriptkitties/p6-Config") found. META6.json has "3.0.4" but latest 'git tag' is "v3.0.3"

**Comment by AntonOks** [comment]
@Tyil ping

**Comment by AntonOks** [comment]
> @Tyil ping

@Tyil @Beagon @nyanpasu - ping ping

**Comment by Beagon** [comment]
@AntonOks I've added 3.0.4 as a new tag. This should resolve your issue.
